// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// MyresourceListerExpansion allows custom methods to be added to
// MyresourceLister.
type MyresourceListerExpansion interface{}

// MyresourceNamespaceListerExpansion allows custom methods to be added to
// MyresourceNamespaceLister.
type MyresourceNamespaceListerExpansion interface{}
